### ISSUE TITLE
AppVeyor failing

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-build-all-feedstock#2]
```
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 194, in main
    args_func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 474, in args_func
    args.func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 423, in execute
    include_recipe=args.include_recipe)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 417, in build
    m.parse_again(permit_undefined_jinja=False)
  File "C:\conda\lib\site-packages\conda_build\metadata.py", line 351, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja))
  File "C:\conda\lib\site-packages\conda_build\metadata.py", line 628, in _get_contents
    env.globals.update(context_processor(self, path))
  File "C:\conda\lib\site-packages\conda_build\jinja_context.py", line 65, in context_processor
    ctx = get_environ(m=initial_metadata)
  File "C:\conda\lib\site-packages\conda_build\environ.py", line 165, in get_dict
    m.get_value('source/git_rev')))
  File "C:\conda\lib\site-packages\conda_build\environ.py", line 64, in get_git_build_info
    remote_details = subprocess.check_output(["git", "remote", "-v"], env=env)
  File "C:\conda\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\conda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\conda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

https://github.com/conda/conda-build/issues/820

**Comment by pelson** [comment]
Turned out to be a conda-build bug.
